import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.scss";

import Provider from "./_trpc/Provider";

const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600"],
	subsets: ["devanagari"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={poppins.className} suppressHydrationWarning={true}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
